### PR TITLE
Add selector to preview form

### PR DESCRIPTION
**Pull request by tylers-username**
Adds Increment ID and Customer ID selector to preview form.

https://i.imgur.com/V0xjDCu.jpg
https://i.imgur.com/5nAP9uz.jpg
https://i.imgur.com/xN7aMxj.jpg

### CODE REVIEW

**Comment by mzeis** [comment]
Hello Tyler,

thank you for contributing! I'm on the road at the moment but I'll take care of it next week.

**Comment by mzeis** [comment]
Hello Tyler,

can I ask you to create the pull request against the `dev` branch as described [here](http://stackoverflow.com/questions/24159036/how-to-modify-a-pull-request-on-github-to-change-target-branch-to-merge-into)? Back then at the Hackathon we only used a `master` branch but to do things properly we should use the `dev` branch that I just created.

**Comment by tylers-username** [comment]
Done.

**Comment by mzeis** [comment]
Closing as this PR was merged into the `dev` branch in #16.

**Pull request closed without merging**
